runexp:
  noise: 1e-5
  numIter: 20
  initialDesign: 10
  saveFolder: ./integrated/reports/
  confFolder: ./integrated/config/
  summaryFolder: ./integrated/summary/
  blueprint: blueprint.yaml
  conf: topology.yaml
  topic: jsontest
  sleep_time: 10000
  metricPoll: 1000
  expTime: 300000
  replication: 5
services:
  - servicename: "broker"
    URL: "http://localhost:8082"
  - servicename: "deployment.service"
    URL: "http://10.50.51.4"
    container: "d9d639b0-99dd-405d-8922-920cc55887c5"
    username: "dice"
    password: "o73K32-b98f89n"
    tools: "/usr/share/deployment-service/"
  - servicename: "monitoring.service"
    URL: "http://10.50.51.10:5001"
  - servicename: "storm_ui"
    URL: "http://10.50.51.121:8080"
    ip: "10.50.51.121"
    username: "ubuntu"
    password: "WieJSg936wNuacTC195E"
    storm_client: "/usr/share/storm/1.0.1/"
  - servicename: "zookeeper.servers"
    URL: "localhost:2181"
    ip: "127.0.0.1"
application:
  jar_file: storm-starter-1.0.1.jar
  jar_path: URL
  class: org.apache.storm.starter.WordCountTopology
  name: wordcount
  type: storm
vars:
  - paramname: "topology.backpressure.enable" 
    node: ["storm", "nimbus"] 
    options: [true false]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "component.spout_num" 
    node: ["storm", "nimbus"] 
    options: [1 3]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "topology.max.spout.pending" 
    node: ["storm", "nimbus"] 
    options: [100 1000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "topology.sleep.spout.wait.strategy.time.ms"
    node: ["storm", "nimbus"]  
    options: [10 100]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "component.split_bolt_num"
    node: ["storm", "nimbus"]  
    options: [3 6]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "component.count_bolt_num" 
    node: ["storm", "nimbus"]  
    options: [3 6]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
  - paramname: "storm.messaging.netty.min_wait_ms"  
    node: ["storm", "nimbus"] 
    options: [10 1000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
